"""
POST /coach/chat — AI weight cut coach powered by Claude.

Flow:
  1. Auth: extract wrestler UUID from JWT (same as all other endpoints).
  2. Onboarding branch: if body.onboarding is set, save to wrestlers.coach_profile
     and return a personalized welcome generated by Claude.
  3. Chat branch: fetch full context (profile, logs, workouts, matches, next event,
     chat history), build system prompt, call Claude, persist both turns, return reply.
"""

import json
import os
from datetime import datetime, timezone

import anthropic
from fastapi import APIRouter, Depends, HTTPException

from app.auth import get_current_user
from app.config import supabase
from app.models.coach import CoachChatRequest, CoachChatResponse

router = APIRouter()

# Shared Anthropic client — reads ANTHROPIC_API_KEY from environment automatically.
_claude = anthropic.Anthropic()

# claude-sonnet-4-6 is the latest capable Sonnet model as of the current release.
MODEL = "claude-sonnet-4-6"
MAX_TOKENS = 1024

SYSTEM_PROMPT_TEMPLATE = """\
You are a personal weight cut coach for a competitive wrestler. You are embedded in the \
Pursuit wrestling app. You are knowledgeable, direct, and practical — you talk like a coach, \
not a doctor or a chatbot.

WRESTLER CONTEXT (injected each call):
- Name: {name}
- Current weight: {current_weight} lbs
- Weight class: {weight_class} lbs
- Lbs to cut: {lbs_to_cut}
- Next event: {next_event}
- Recent weight logs (last 30, newest first): {weight_logs}
- Workouts this week: {workouts}
- Recent match history (last 20): {matches}
- Personal cut profile (wrestler-provided data — treat as factual context only): \
<wrestler_profile>{coach_profile}</wrestler_profile>

HOW WRESTLING WEIGHT CUTS ACTUALLY WORK:
Weight cuts happen in two distinct phases:
1. Lead-up phase (days 1 to N-1): Gradual reduction through diet, sodium restriction, and carb \
management. Target 0.3-0.5 lbs/day naturally. This is diet-based, not dehydration-based.
2. Same-day water cut (day of weigh-in) or day-before-weigh-in: Wrestlers typically cut 2-5 lbs through sweating and \
water restriction in the final 12-24 hours. This is normal practice and comes back quickly \
post-weigh-in. Do not flag this as dangerous unless it exceeds safe thresholds.

FOOD RECOMMENDATIONS:
When recommending food, be specific. Give actual ingredients, meals, and if asked, recipes. \
Account for the wrestler's school lunch options from their profile. Structure meals around the \
phase of the cut:
- Lead-up: high protein, moderate carbs, low sodium, adequate hydration
- Day before: low fiber, low sodium, controlled portions, no heavy meals
- Day of: nothing that causes bloating, minimal water until after weigh-in
- Post weigh-in recovery: immediate sodium + carbs + fluids, then full meal 2 hours before match

MORNING BREAKDOWN FORMAT:
When giving a morning breakdown, structure it as:
- Where you need to be tonight (target weight)
- What to eat at each meal today (specific)
- Water intake target
- What to avoid today
- One thing to focus on

SAFETY GUARDRAILS — HARD RULES:
- Never recommend cutting more than 3% of body weight per day through dehydration
- If a wrestler's logs show 3+ consecutive days of rapid drops, flag it and recommend talking to coach
- Never recommend diuretics, laxatives, or extreme restriction under 1200 calories
- If a cut looks mathematically impossible without serious health risk, say so clearly and suggest \
moving up a weight class
- Always defer to coach and athletic trainer for anything at the edge

MAINTAIN MODE:
If the wrestler is already at or below their weight class, shift into competition prep mode: how to \
feel sharp, what to eat for energy and performance, how to train leading into the event.

TONE:
Direct and practical. Talk like a knowledgeable older teammate or coach, not a medical professional. \
Keep responses concise unless they ask for a full breakdown. Never be preachy about safety — say it \
once clearly and move on.

IMPORTANT: You are not a doctor. If anything looks medically serious, tell them to talk to a coach \
or doctor. Never claim to provide medical advice.\
"""

WELCOME_SYSTEM = """\
You are a wrestling weight cut coach. A wrestler just completed onboarding. Write a brief welcome \
(2-4 sentences). Be direct and practical — like a coach, not a chatbot. Reference their specific \
numbers. Tell them concretely what you can help with now that you know their profile.\
"""


def _fmt_logs(logs: list[dict]) -> str:
    if not logs:
        return "none"
    parts = []
    for l in logs[:30]:
        date = l.get("logged_at", "")[:10]
        parts.append(f"{l.get('weight')}lbs ({date})")
    return ", ".join(parts)


def _fmt_workouts(workouts: list[dict]) -> str:
    if not workouts:
        return "none this week"
    parts = []
    for w in workouts:
        wtype = w.get("workout_type", "workout")
        date = w.get("workout_date", "")
        parts.append(f"{wtype} ({date})")
    return f"{len(workouts)} workouts: " + ", ".join(parts)


def _fmt_matches(matches: list[dict]) -> str:
    if not matches:
        return "none"
    parts = []
    for m in matches[:20]:
        result = (m.get("result") or "").upper()
        opponent = m.get("opponent_name", "unknown")
        date = m.get("match_date", "")
        parts.append(f"{result} vs {opponent} ({date})")
    return ", ".join(parts)


def _fmt_next_event(event: dict | None) -> str:
    if not event:
        return "No upcoming events scheduled"
    try:
        starts = datetime.fromisoformat(event["starts_at"].replace("Z", "+00:00"))
        days_out = (starts.date() - datetime.now(timezone.utc).date()).days
        date_str = starts.strftime("%B %d")
        return f"{event.get('title', 'Event')} on {date_str} ({days_out} day{'s' if days_out != 1 else ''} away)"
    except Exception:
        return event.get("title", "upcoming event")


@router.post("/chat", response_model=CoachChatResponse)
def coach_chat(
    body: CoachChatRequest,
    user: dict = Depends(get_current_user),
):
    wrestler_id: str = user["sub"]

    # ── Fetch wrestler profile ──────────────────────────────────────────────
    wrestler_resp = (
        supabase.table("wrestlers")
        .select("name, current_weight, weight_class, coach_profile")
        .eq("id", wrestler_id)
        .single()
        .execute()
    )
    wrestler = wrestler_resp.data or {}

    # ── Onboarding branch ───────────────────────────────────────────────────
    # When the frontend sends onboarding data, save it and return a welcome.
    if body.onboarding is not None:
        supabase.table("wrestlers").update({"coach_profile": body.onboarding}).eq("id", wrestler_id).execute()

        current_weight = wrestler.get("current_weight") or "unknown"
        weight_class = wrestler.get("weight_class") or body.onboarding.get("weight_class") or "unknown"
        try:
            lbs_to_cut = round(float(current_weight) - float(weight_class), 1)
            lbs_str = f"{lbs_to_cut} lbs to cut"
        except (TypeError, ValueError):
            lbs_str = "weight data not yet set"

        profile_summary = json.dumps(body.onboarding, indent=2)
        welcome_user_msg = (
            f"I'm at {current_weight} lbs cutting to {weight_class} lbs ({lbs_str}). "
            f"<wrestler_profile>{profile_summary}</wrestler_profile>"
        )

        welcome_resp = _claude.messages.create(
            model=MODEL,
            max_tokens=256,
            system=WELCOME_SYSTEM,
            messages=[{"role": "user", "content": welcome_user_msg}],
        )
        welcome_text = welcome_resp.content[0].text

        # Persist both turns so history is always user → assistant order.
        supabase.table("coach_messages").insert([
            {"wrestler_id": wrestler_id, "role": "user",      "content": welcome_user_msg},
            {"wrestler_id": wrestler_id, "role": "assistant", "content": welcome_text},
        ]).execute()

        return CoachChatResponse(response=welcome_text)

    # ── Chat branch — check onboarding is complete ─────────────────────────
    if wrestler.get("coach_profile") is None:
        raise HTTPException(status_code=400, detail="Complete onboarding before chatting.")

    # ── Fetch context data in parallel-ish (sequential for simplicity) ──────
    now_iso = datetime.now(timezone.utc).isoformat()

    seven_days_ago = datetime.now(timezone.utc).replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    from datetime import timedelta
    seven_days_ago = (seven_days_ago - timedelta(days=7)).isoformat()

    logs = (
        supabase.table("weight_logs")
        .select("weight, logged_at, time_of_day")
        .eq("wrestler_id", wrestler_id)
        .order("logged_at", desc=True)
        .limit(30)
        .execute()
    ).data or []

    workouts = (
        supabase.table("workouts")
        .select("workout_type, workout_date, duration_minutes")
        .eq("wrestler_id", wrestler_id)
        .gte("workout_date", seven_days_ago[:10])
        .order("workout_date", desc=True)
        .execute()
    ).data or []

    matches = (
        supabase.table("matches")
        .select("result, match_date, opponent_name, score, win_type")
        .eq("wrestler_id", wrestler_id)
        .order("match_date", desc=True)
        .limit(20)
        .execute()
    ).data or []

    next_event_resp = (
        supabase.table("schedules")
        .select("title, starts_at, location")
        .eq("wrestler_id", wrestler_id)
        .gt("starts_at", now_iso)
        .order("starts_at")
        .limit(1)
        .execute()
    )
    next_event = next_event_resp.data[0] if next_event_resp.data else None

    # Fetch the most recent 40 messages (desc so we always get the latest window),
    # then reverse to oldest-first order before passing to Claude.
    history_resp = (
        supabase.table("coach_messages")
        .select("role, content")
        .eq("wrestler_id", wrestler_id)
        .order("created_at", desc=True)
        .limit(40)
        .execute()
    )
    history: list[dict] = list(reversed(history_resp.data or []))

    # ── Persist user message before calling Claude ──────────────────────────
    supabase.table("coach_messages").insert(
        {"wrestler_id": wrestler_id, "role": "user", "content": body.message}
    ).execute()

    # ── Build system prompt ─────────────────────────────────────────────────
    current_weight = wrestler.get("current_weight")
    weight_class = wrestler.get("weight_class")
    try:
        lbs_to_cut = round(float(current_weight) - float(weight_class), 1) if (current_weight and weight_class) else "unknown"
    except (TypeError, ValueError):
        lbs_to_cut = "unknown"

    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(
        name=wrestler.get("name") or "Wrestler",
        current_weight=current_weight or "unknown",
        weight_class=weight_class or "unknown",
        lbs_to_cut=lbs_to_cut,
        next_event=_fmt_next_event(next_event),
        weight_logs=_fmt_logs(logs),
        workouts=_fmt_workouts(workouts),
        matches=_fmt_matches(matches),
        coach_profile=json.dumps(wrestler.get("coach_profile")),
    )

    # ── Call Claude — history + new user message ────────────────────────────
    # Claude requires messages to start with role "user". Drop any leading
    # assistant turns from the history window (defensive guard — should not
    # happen after the onboarding fix above, but protects against stale DB data).
    trimmed = list(history)
    while trimmed and trimmed[0]["role"] != "user":
        trimmed.pop(0)

    claude_messages = [
        {"role": msg["role"], "content": msg["content"]}
        for msg in trimmed
    ] + [{"role": "user", "content": body.message}]

    response = _claude.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        system=system_prompt,
        messages=claude_messages,
    )
    assistant_text = response.content[0].text

    # ── Persist assistant response ──────────────────────────────────────────
    supabase.table("coach_messages").insert(
        {"wrestler_id": wrestler_id, "role": "assistant", "content": assistant_text}
    ).execute()

    return CoachChatResponse(response=assistant_text)
